# Generated by Django 3.2.19 on 2023-06-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='descripcion',
            new_name='TipoPersona',
        ),
    ]
